name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build and push FastAPI backend
      - name: Build, Tag, and Push Housing API image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          ECR_REGISTRY=739623013917.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY=housing-api

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # Build and push Streamlit frontend
      - name: Build, Tag, and Push Housing Streamlit image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          ECR_REGISTRY=739623013917.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY=housing-streamlit

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.streamlit .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # Deploy FastAPI ECS service
      - name: Deploy housing-api-service
        run: |
          aws ecs update-service \
            --cluster housing-cluster \
            --service housing-api-service \
            --force-new-deployment

      # Deploy Streamlit ECS service
      - name: Deploy housing-streamlit-service
        run: |
          aws ecs update-service \
            --cluster housing-cluster \
            --service housing-streamlit-service \
            --force-new-deployment
